spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.94.169.32:3306/materialgene?useSSL=false
    url: jdbc:mysql://localhost:3306/materialgene?useSSL=false
    username: root
#    password: 191903
    password: 123456

server:
  port: 8080
